### PR TITLE
Display from bottom + Upgrade dependencies + Migrate to new gesture API

### LINKED ISSUE #3: How to make toast appear from bottom?
Hi,

How to make the toast appear from bottom of the screen?

I've tried absolute position but it doesn't seem to be working.

### PR DESCRIPTION
**Pull request by mrkpatchaa**
- [x] Add an option to display toasts at the bottom
- [x] Add an option to use SafeArea
- [x] Upgrade dependencies
- [x] Upgrade to new Gesture Api
- [x] Bump npm version to keep the last one working
- [x] Upgrade example app dependencies + CustomToaster
- [x] Fix container swipe animation for bottom display
- [x] Fixes #3

### CODE REVIEW

**Comment by kubilaysalih** [comment]
Dude, you rewrote the whole library. 🥳 I don't have pc access right now, I'll check tonight. Thank you very much.

**Comment by mrkpatchaa** [comment]
I tried my best because I am not an expert of reanimated. 
But I tested and everything is working right now.
Let me know what you think.
Really happy to help and looking forward for your review.

**Comment by kubilaysalih** [comment]
I guess the buttons and views are not clickable when position is bottom on android. :(

@mrkpatchaa

**Comment by mrkpatchaa** [comment]
I was mainly testing on iPhone. Let me check Android.

**Pull request merged**
